### ISSUE TITLE
Still necessary?

### ISSUE THREAD

**Issue by mrstegeman** [tomasy/zigbee-conbee-adapter#12]
Is there a reason to keep this add-on around, since the standard Zigbee adapter has full, stable support for the ConBee dongles now?

**Comment by ulph** [comment]
just chiming in after an afternoon of troubleshooting 3rd party lights

yes and no, imo

I aquired the OSRAM+ light, as well as a generic 5050 rgbw strip using a custom driver.

Neither the native Zigbee plugin nor this plugin exposes the full control.

Using this plugin, I get a "color temperature light".

Using the official zigbee plugin, I get an rgb light.

Here's a dump from _myhost/api/user/lights_

```json
{
  "ctmax": 666,
  "ctmin": 125,
  "etag": "SCRUBBED",
  "hascolor": true,
  "manufacturername": "OSRAM",
  "modelid": "LIGHTIFY Outdoor Flex RGBW",
  "name": "osram+",
  "state": {
    "alert": "none",
    "bri": 252,
    "colormode": "ct",
    "ct": 370,
    "effect": "none",
    "hue": 0,
    "on": true,
    "reachable": false,
    "sat": 0,
    "xy": [
      0.3805,
      0.3769
    ]
  },
  "swversion": "V1.04.93",
  "type": "Extended color light",
  "uniqueid": "SCRUBBED"
}
```

@mrstegeman I would of course rather see the official plugin working fully with these bulbs, and I am happy to help with any logs/dumps whatnot.

**Comment by mrstegeman** [comment]
@ulph thats not really a limitation of the adapter. That’s more of a design decision from the gateway. See: https://github.com/mozilla-iot/gateway/issues/1378 (and all the linked issues)

**Comment by mrstegeman** [comment]
I've removed this add-on from the official add-on list. If anyone can provide a good justification for it being re-added, I will consider it.
